# Generated by Django 4.0.5 on 2022-06-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('weather', models.CharField(max_length=200, verbose_name='날씨')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('mainphoto', models.FileField(blank=True, null=True, upload_to='diaryPics')),
            ],
        ),
    ]
